spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  mvc:
    static-path-pattern: "/static/**"
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
    cache: false
    check-template-location: true
mybatis:
  mapper-locations: /mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
server:
  port: 443

