spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  mvc:
    static-path-pattern: "/static/**"
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
    cache: false
    check-template-location: true
mybatis:
  mapper-locations: /mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: 'asdf664417'


#    enabled: true
#    key-alias: ayokeystore
#    key-store: ayokeystore.pkcs12
#    key-store-password: 'asdf664417'
#    key-password: 'asdf664417'
#    trust-store: ayotrust.pkcs12
#    trust-store-password: 'asdf664417'

